services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
      - 5005:5005
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.17.1"
      MAX_MEMORY: "2G"
      ONLINE_MODE: "TRUE"
    volumes:
      - ./minecraft:/data